#include <unistd.h> // read, write, close
#include <fcntl.h>  // open
#include <stdlib.h> // exit
#include <stdio.h>  // perror
#include <errno.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <pwd.h>
#include <time.h>
#include <limits.h>

#define handle_error(msg)\
do{\
	perror(msg);\
	exit(1);\
}while(0)

char* append(char* string1, char* string2){
	size_t dim = (strlen(string1)) + (strlen(string2) + 1);
	char *tmp = malloc(dim * sizeof(char));
    strcpy(tmp, string1);
    strcat(tmp, string2);
   	return tmp;
}

void change_parallels_resolution(){	
	// crea file desktop
	char* filename = "40-prltools.conf";
	FILE * f = fopen(filename, "w");
	if(f == NULL)	handle_error("Impossibile creare il file!");

	char* init = "#\n# X.Org server configuration file generated by Parallels Guest Tools & LucasMac.\n#\n\n# Parallels Video section\n";
	char* tmp1 = append(init, "Section \"Device\"\n\tIdentifier      \"Parallels Video\"\n\tDriver  \"prlvideo\"\nEndSection\n\n");
	char* tmp2 = append(tmp1, "# Parallels Monitor section\nSection \"Monitor\"\n\tIdentifier	\"Parallels Monitor\"\n\tVendorName	\"Parallels Inc.\"\n\tModelName	\"Parallels Monitor\"\nEndSection\n\n");
	char* tmp3 = append(tmp2, "# Parallels Screen section\nSection \"Screen\"\n\tIdentifier	\"Parallels Screen\"\n\tDevice	\"Parallels Video\"\n\tMonitor	\"Parallels Monitor\"\n\tOption	\"NoMTRR\"\n\tSubSection	\"Display\"\n\t	Depth	24\n\t	Modes	\"1440x900\"\n\tEndSubSection\nEndSection\n\n");
	char* tmp4 = append(tmp3, "# DefaultFlags section\nSection \"ServerFlags\"\n\tOption	\"AllowEmptyInput\"	\"yes\"\n\tOption	\"AutoAddDevices\"	\"yes\"\nEndSection\n\n");
	char* tmp5 = append(tmp4, "# DefaultLayout section\nSection \"ServerLayout\"\n\tIdentifier	\"DefaultLayout\"\n\tScreen	\"Parallels Screen\"\nEndSection\n");
	
	fprintf(f, "%s\n", tmp5);
	
	fclose(f);
	// rimuovi /usr/share/X11/xorg.conf.d/40-prltools.conf

		// controllo se il file già è esistente!
	char cwd[PATH_MAX];
  	char* current_dir = getcwd(cwd, sizeof(cwd));	// directory corrente
  	if(current_dir == NULL)	handle_error("Errore: Impossibile ricavare la directory in uso!");
  	
  	char* tmp6 = append(current_dir, "/");
  	char* fileInCurrentDir = append(tmp6, filename);

  	char* paralFileInDir = "/usr/share/X11/xorg.conf.d/";
  	int ret = chdir(paralFileInDir);
  	if(ret == -1)	handle_error("Errore: impossibile cambiare directory");


  	struct stat buffer;   
  	int fileExist = (stat (filename, &buffer) == 0);
  	if(fileExist){
  		system("sudo rm 40-prltools.conf");

  		ret = chdir(current_dir);
  		if(ret == -1)	handle_error("Errore: impossibile cambiare directory");
  		char* copyCommand = append("sudo cp 40-prltools.conf ", paralFileInDir);
  		system(copyCommand);
  		
  		ret = remove("40-prltools.conf");
  		if(ret != 0)	handle_error("Errore: Impossibile eliminare la spazzatura!");
  		free(copyCommand);
  	}else handle_error("\n\nIl file non esiste nella directory, quindi suppongo che non hai installato parallels!");

  	free(tmp6);
	free(tmp5);
	free(tmp4);
	free(tmp3);
	free(tmp2);
	free(tmp1);
}


int main(int argc, char *argv[]){
	change_parallels_resolution();
	return 0;
}
